---

- name: user and group handling
  when:
    - home_assistant_user.owner != "root"
  block:
    - name: create home-assistant group
      ansible.builtin.group:
        name: "{{ home_assistant_user.group }}"
        state: present
        system: true

    - name: create home-assistant user
      ansible.builtin.user:
        comment: "Home Assistant"
        name: "{{ home_assistant_user.owner }}"
        groups: "{{ home_assistant_user.group }}"
        append: false
        home: "{{ home_assistant_user.home }}"
        shell: /sbin/nologin
        system: true
        createhome: true
        home: /nonexistent

    - name: create directory
      file:
        path: "{{ home_assistant_user.home }}"
        state: directory
        mode: 0775
        owner: "{{ home_assistant_user.owner }}"
        group: "{{ home_assistant_user.group }}"

    - name: create storage directory
      file:
        path: "{{ home_assistant_user.home }}/.storage"
        state: directory
        mode: 02775
        owner: "{{ home_assistant_user.owner }}"
        group: "{{ home_assistant_user.group }}"
