---

- name: user and group handling
  when:
    - home_assistant_user.owner != "root"
  block:
    - name: create home-assistant group
      ansible.builtin.group:
        name: "{{ home_assistant_user.group }}"
        state: present
        system: true

    - name: create home-assistant user
      ansible.builtin.user:
        comment: "Home Assistant"
        name: "{{ home_assistant_user.owner }}"
        groups: "{{ home_assistant_user.group }}"
        append: false
        home: "{{ home_assistant_user.home }}"
        shell: /sbin/nologin
        system: true
        createhome: true

    - name: create directory
      ansible.builtin.file:
        state: directory
        path: "{{ home_assistant_user.home }}"
        owner: "{{ home_assistant_user.owner }}"
        group: "{{ home_assistant_user.group }}"
        mode: 02775

    - name: create storage directory
      ansible.builtin.file:
        state: directory
        path: "{{ home_assistant_user.home }}/.storage"
        owner: "{{ home_assistant_user.owner }}"
        group: "{{ home_assistant_user.group }}"
        mode: 02775

- name: add user {{ home_assistant_user.owner }} to groups
  ansible.builtin.user:
    name: "{{ home_assistant_user.owner }}"
    groups: "{{ item }}"
    append: true
  loop:
    "{{ home_assistant_groups | sort | unique }}"
  when:
    - home_assistant_groups is defined
    - home_assistant_groups | count > 0
