---

- name: converge
  hosts: instance
  any_errors_fatal: false
  become: false

  environment:
    NETRC: ''

  roles:
    - role: ansible-home-assistant

  post_tasks:
    - name: wait for home-assistant to listen on its port
      ansible.builtin.wait_for:
        port: "{{ home_assistant_port | default(8123) }}"
        timeout: 600
